export { KANJIVG_VIEWBOX, kanjiData } from './data/strokes';
export type { KanjiStrokes } from './data/strokes';
export { readings } from './data/readings';
export type { Reading } from './data/readings';
export { pathToPolyline, polylineLength, resample } from './path';
export type { Point } from './path';
export { judgePolyline, judgeReasonLabels, judgeStroke } from './judge';
export type { StrokeVerdict } from './judge';
export { emptyMastery, isPassed, markPassed, passedCount, restoreMastery } from './progress';
export type { Mastery, Mode } from './progress';
